text_model:
  class: uwul.model.LigerCCELlama
  factory: from_config
  args:
  - ./config/arch/NanoLLaMA-25m.json
  kwargs:
    vocab_size: 32013
    torch_dtype: float16
    attn_implementation: flash_attention_2
    use_fused: true
tokenizer:
  class: transformers.LlamaTokenizer
  factory: from_pretrained
  args:
  - KBlueLeaf/TIPO-500M
