text_model:
  class: transformers.LlamaForCausalLM
  factory: from_pretrained
  args:
  - KBlueLeaf/TIPO-200M
  kwargs:
    torch_dtype: float16
    attn_implementation: flash_attention_2
tokenizer:
  class: transformers.LlamaTokenizer
  factory: from_pretrained
  args:
  - KBlueLeaf/TIPO-200M
