text_model:
  class: uwul.model.AutoModelForCausalLMFactory
  factory: from_config
  args:
  - ./config/arch/NanoLLaMA-500m.json
  kwargs: #config overrides
    vocab_size: 32013
    torch_dtype: float16
    attn_implementation: flash_attention_2
tokenizer:
  class: transformers.LlamaTokenizer
  factory: from_pretrained
  args:
  - KBlueLeaf/TITPOP-200M-dev
