[lightning]
    epochs=5
    batch_size=32
    dataloader_workers=0
    grad_acc={0=1, 1=2, 2=4, 3=8, 4=16} # epoch: grad_acc
    devices=[0]
    precision="bf16-true"
    grad_clip=0.1
    grad_ckpt=true

    [lightning.logger]
        name="uwuLLM-test"
        project="uwuLLM-test"
        version="" # Empty for random id
        offline=true


[trainer]
    name="test"
    lr=1e-4
    optimizer="uwul.trainer.optimizers.AdamWFP16"
    opt_configs = {"weight_decay"= 0.01, "betas"= [0.9, 0.98]}
    use_warm_up=true
    warm_up_period = 10


[dataset]
    factory = {class = "dataset.guanaco.GuanacoDatasetFactory"}
    split = "mini"
    [dataset.processor_config]
        cutoff_len = 128
        train_on_inputs = true


[model]
    config="./config/model/tinyllama.yaml"