seed=3408

[lightning]
    epochs=2
    batch_size=32
    dataloader_workers=8
    grad_acc={0=16} # epoch: grad_acc
    devices=[0, 1, 2, 3]
    precision="16-mixed"
    grad_clip=0.1
    grad_ckpt=true

    [lightning.logger]
        name="TIPO-200M_rev2"
        project="NanoLLaMA"
        version="" # Empty for random id
        offline=false


[trainer]
    name="TIPO-200M"
    lr=2e-5
    optimizer="torch.optim.AdamW"
    opt_configs = {"weight_decay"= 0.01, "betas"= [0.9, 0.98]}
    lr_scheduler = "torch.optim.lr_scheduler.CosineAnnealingLR"
    lr_sch_configs = {"T_max"= -1, "eta_min"= 1e-6} # -1 for auto
    use_warm_up=false
    warm_up_period = 10


[dataset]
    factory = {class = "dataset_private.titpop.TITPOPDatasetFactory"}
    split = ["danbooru", "coyo"]
    [dataset.processor_config]
        cutoff_len = 1024


[model]
    config="./config/model/tipo-200m.yaml"